version: '3.3'

networks:
  user_groups2:
    external: false

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - user_groups2
  user_groups_api:
    build:
      context: api
      dockerfile: Dockerfile
    networks:
      - user_groups2
  user_groups_cli:
    build:
      context: cli
      dockerfile: Dockerfile
    networks:
      - user_groups2

# Names our volume
volumes:
  mysql_db: